version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-01
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run

